#!/usr/bin/env bash
# print best school 10 times and replace 4th position with bad luck and 8th position with good luck
i=0
while ((i < 10))
do
if ((i == 3))
then
echo "bad luck"
elif ((i == 7))
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
