#!/usr/bin/env bash
# loops and replacement in certain position
i=1
while ((i <= 20))
do
case $i in
5)
echo "bad luck from China"
echo "$i"
;;
10)
echo "bad luck from Japan"
echo "$i"
;;
18)
echo "bad luck from Italy"
echo "$i"
;;
*)
echo "$i"
;;
esac
((i++))
done
